version: "3.8"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'database'
    ports:
      - "5432:5432"
    volumes:
      - pgdate:/var/lib/postgresql/data
    env_file: .env
    restart: always
volumes:
  pgdate:
